config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "users#index"
  get "/register", to: "users#register"

  get "/login", to: "pages#index"

  resource :sessions, only: [:create, :destroy]
  get "/sessions", to: "sessions#login"
  resources :users
  get "/dashboard_posts/:id", to: "api/posts#dashboard_get_more_posts"
  get "/user_posts/:id", to: "api/posts#get_more_posts"
  get "/user/:id", to: "users#show"
  post "/sessions/gps_position", to: "api/sessions#save_location_by_gps"
  post "/posts", to: "api/posts#create"
  post "/post_by_ip", to: "api/posts#create_by_ip"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :posts
  validates :username, uniqueness: true, presence: true
  validates :password, presence: true
end

app/models/weather.rb
# frozen_string_literal: true

class Weather < ApplicationRecord
  belongs_to :post
end

app/controllers/api/posts_controller.rb
# frozen_string_literal: true

class Api::PostsController < ApplicationController
  include PostsHelper

  def create
    post = create_post
    if post.save
      render json: post
    end
    false
  end

  def create_by_ip
    post = create_post_by_ip
    if post.save
      render json: post
    end
    false
  end

  def get_more_posts
    render json: get_next_10_posts
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  
  include UsersHelper
  include SessionsHelper

  def index
    if logged_in?
      @user = get_current_user_info
      render :dashboard
    else
      render :login
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  
  def new

  end
  
  def create

  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  include SessionsHelper

  def create
    if login_is_valid?
      login_user
      redirect_to "/"
    else
      @error = "Username or password invalid"
      render :login
    end
  end

  def login
    render :login
  end

  def destroy
    delete_user_session
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include UsersHelper

  def index
    if logged_in?
      @user = current_user
      @posts = get_user_first_10_posts
      render :show
    else
      render :login
    end
  end

  def create
    user = new_user
    if user.save
      session[:user_id] = user.id
      redirect_to "/"
    else
      @error = "Username or password invalid"
      render "register"
    end
  end

  def show
    @user = User.find_by(username: params[:id])
    @posts = get_user_first_10_posts
    render :show
  end

  def register
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def create_post
    create_new_post(call_weather_api_with_lat_lon)
  end

  def create_post_by_ip
    city = find_city
    if city
      return create_new_post(call_weather_api_with_ip)
    else
      return create_post_without_city
    end
  end

  def find_city
    query = find_city_with_ip
    return query["city"] if query["city"]
    return query["region_name"] if query["region_name"]
  end

  def create_new_post(response)
    Post.new(
      temp: response["main"]["temp"].to_i,
      city: response["name"],
      country: response["sys"]["country"],
      lon: response["coord"]["lon"],
      lat: response["coord"]["lat"],
      weather_brief: response["weather"][0]["main"],
      weather_description: response["weather"][0]["description"],
      content: params[:content],
      user_id: session[:user_id]
    )
  end

  def create_post_without_city
    Post.new(
      content: params[:content],
      user_id: session[:user_id]
    )
  end

  def get_next_10_posts
    Post.where(user: params[:id]).order("created_at desc").limit(10).offset(params[:offset])
  end

  def call_weather_api_with_lat_lon
    HTTParty.get("http://api.openweathermap.org/data/2.5/weather?lat=#{params[:lat].to_f}&lon=#{params[:lon].to_f}&appid=#{ENV['WEATHER_API_KEY']}")
  end

  def find_city_with_ip
    HTTParty.get("http://api.ipstack.com/#{params[:ip]}?access_key=#{ENV['IPSTACK_KEY']}")
  end

  def call_weather_api_with_ip
    HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{find_city}&appid=#{ENV['WEATHER_API_KEY']}")
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def login_user
    user = User.find_by(username: params[:username])
    session[:user_id] = user.id
    session[:username] = user.username
  end

  def logged_in?
    !!session[:user_id]
  end

  def login_is_valid?
    user = User.find_by(username: params[:username])
    return user.authenticate(params[:password]) if user
    false
  end

  def delete_user_session
    session[:user_id] = nil
    session[:username] = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def valid_user? (user_id)
    !!User.find_by(id: user_id)
  end

  def new_user
    User.new(username: params[:username], password: params[:password])
  end

  def get_user_first_10_posts
    @user.posts.order("created_at desc").limit(10)
  end
end

app/views/homepage/login.html.erb
  <%= form_tag(sessions_path, :method => 'post', :class => 'login-form', name: 'login-form') do %>
    <%= text_field_tag 'username' %>
    <%= text_field_tag 'password' %>
    <%= submit_tag 'Login', :id => 'Login' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoriasTempo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<div class="blue-background">
  
</div>
<main>
  <div class="main-banner">
    <h2>Memórias do Tempo</h2>
    <h1>Login</h1>
  </div>
  <%= form_tag(sessions_path, :method => 'post', :class => 'login-form', name: 'login-form') do %>
    <%= text_field_tag 'username', nil, class: 'default-form-input' %>
    <%= text_field_tag 'password', nil, class: 'default-form-input', type: 'password' %>
    <%= submit_tag 'Login', :id => 'Login' %>
    <p class="error"> <%= @error %> </p>
    <p class="small">Don't have an account? <a href="/register">Register now</a></p>
  <% end %>
</main>
<div class="clouds"></div>

<script>
  random = () => [Math.floor(Math.random() * 2), Math.floor(Math.random() * 9)]
  randomScale = () => `${random()[0]}.${random()[1]}`
  randomPos = () => [Math.floor(Math.random() * 10), Math.floor(Math.random() * 5)]
  randomPosition = () => { return {x: (randomPos()[0]+2).toString() + randomPos()[0], y: randomPos()[1].toString() + randomPos()[1] } }

  createClouds = () => {
    for (i = 0; i < 15; i++) {
      createCloud(randomScale(),randomPosition())
    }
  }

  createCloud = (size, position) => {
    container = document.createElement('div')
    size[2] % 2 === 0 ? container.className = 'cloud__container' : container.className = 'cloud__container-2'
    cloud = document.createElement('div')
    cloud.className = 'cloud'
    cloudTop = document.createElement('div')
    cloudTop.className = 'cloud__top'
    cloudTopLeft = document.createElement('div')
    cloudTopLeft.className = 'cloud__top-left'
    cloudTopRight = document.createElement('div')
    cloudTopRight.className = 'cloud__top-right'
    cloudBottom = document.createElement('div')
    cloudBottom.className = 'cloud__bottom'
    cloudTop.appendChild(cloudTopLeft)
    cloudTop.appendChild(cloudTopRight)
    cloud.appendChild(cloudTop)
    cloud.appendChild(cloudBottom)
    container.style = `top: ${position.y}vh; left: ${position.x}vw; `

    cloud.style = `transform: scale(${size})`

  // implement night mode.

    container.appendChild(cloud)
    document.querySelector('.clouds').appendChild(container)
  }

  createClouds()
</script>

app/views/users/register.html.erb
<div class="dark-background"></div>

<div class="register-content">
  <div class="main-banner">
    <h2>Memórias do Tempo</h2>
    <h1>Register</h1>
  </div>

  <%= form_tag(users_path, :method => 'post', :class => 'register-form') do%>
    <%= text_field_tag 'username', nil, class: 'default-form-input' %>
    <%= text_field_tag 'password', nil, class: 'default-form-input', type: 'password' %>
    <%= submit_tag 'Submit', :id => 'Register' %>
    <p class="error"><%= @error %></p>
    <p class="small">Already have an account? <a href="/">Login</a></p>
  <% end %>
</div>

<section class="stars-1">
  
</section>
<section class="stars-2">
  
</section>

<div class="shooting-star">
  <div class="shoot"></div>
</div>
  
<section class="moon">
  <div class="dark-hole"></div>
  <div class="light-hole"></div>
  <div class="light-hole-2"></div>
</section>


<script>
function createStar(number){
  star = document.createElement('div')
  star.className = 'star'
  rand = random()
  star.style = `top: ${rand[0]}vh; left: ${rand[1]}vw`
  document.querySelector('.stars-' + number).appendChild(star)
}

function random(){
  rand = [Math.floor(Math.random() * 100), Math.floor(Math.random() * 100)]
  return rand
}

while (document.querySelectorAll('.star').length < 400) {
  createStar(1)
  createStar(2)
}

function shootStar(number){
  space = document.querySelector('.shooting-star')
  star = document.createElement('div')
  star.className = "shoot" + number
  star.style = 'top:' + Math.floor(Math.random() * 100) + '%';
  space.appendChild(star)
}

setInterval(()=>{
  shootStar(1)}, 2400
)
setInterval(()=>{
 shootStar(2) 
}, 2100)


</script>

app/views/users/show.html.erb
<div class="header">
  <div class="header__profile">
    <div class="header__profile--picture"></div>
    <h3> <%= @user[:username] %> </h3>
  </div>
  
  <% if logged_in? && current_user.id === @user[:id] %>  
    <%= form_tag posts_path, method: 'post', class: 'post-form' do %>
      <%= text_field 'content', nil, placeholder: 'Write something...', class: 'post-form__input'  %>
      <%= submit_tag 'Post', id: 'new_post' %>
    <% end %>

    <%= form_tag sessions_path, method: 'delete', class: 'logout-form', name: 'logout-form' do %>
      <%= submit_tag 'Logout', id: 'Logout' %>
    <% end %>  
  <% end %>
</div>

<div class="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <p class="post__content"><%= post.content %></p>
      <div class="post__footer">
        <p class="post__weather--text"><%= post.weather_description %></p>
        <p class="post__footer--time"><%= post.created_at %></p>
        <p class="post__footer--city"><%= post.city %></p>
      </div>
    </div>
  <% end %>  
</div>

<script>  
  let offset = 10
  const user_id = '<%= @user[:id] %>'
  window.addEventListener('scroll', (e) => {fetchMoreUserPosts(e, user_id) })
  <% if logged_in? && current_user.id === @user[:id] %>
    document.querySelector('#new_post').addEventListener('click', e => {
      e.preventDefault()
      const ip = '<%= request.remote_ip %>'
      const content = e.target.previousElementSibling.value
      navigator.geolocation.getCurrentPosition(
        position => postMemory(content, position, '<%= form_authenticity_token %>'),
        error => postMemory(content, ip, '<%= form_authenticity_token %>')
      )
    })
  <% end %>

convertAllHours()
</script>